Mailboxes
racket/racket7 pull request #5
Opened 2017-05-15 17:03 UTC by spall

Implementation of racket thread mailboxes.  

Run time of thread-ring benchmark is around 3 minutes and is 2 seconds when run in regular racket for an n of 1000000.  Not sure yet what is causing this slowdown.

A simpler benchmark with 2 threads (1 sender, 1 receiver) sending and receiving 1000000 messages runs in about 2.25 seconds.

2017-05-18 00:30 UTC, mflatt commented
It's difficult to review in GitHub with multiple commits, so I'll comment here this time. For the next round, can you squash the commits to make it easier to review?

For the mailbox queue, I think using "../common/queue.rkt" would be better. (I know it's not obvious that "../common/queue.rkt" exists, and I'm not certain that "../common" is a good idea.)

Please spell out "mailbox" in the field name, since the abbreviation "mbx" won't be immediately obvious.

The `thread-send` function incorrectly calls `fail-thunk` in atomic mode. A good pattern to use is `((atomically ...))` where the `atomically` body returns a thunk to run out of atomic mode. Drop the `#:undelay-break?` argument; I've pushed a repair and hopefully improved explanation related to that.

Consider using the `((atomically ...))` pattern in `thread-receive`. Don't ignore the result of `thread-internal-suspend!`; instead, apply it to perform the `engine-block` operation and to correctly check for breaks. Use the `interrupt-callback` and and `retry-callback` arguments to move the thread out of and back into mail-waiting mode, which should do the right thing if the thread receives a break.

Thanks!

2017-05-23 17:13 UTC, spall commented
Hi Matthew,

I think I made all the requested changes to mailboxes, plus a change to the queue code.  I tried to squash all the latest relevant mailbox commits into one commit.  Hopefully this is easier for you to review!

Sarah

2017-05-23 18:55 UTC, samth requested changes

2017-05-23 18:55 UTC, samth commented on racket/src/thread/thread.rkt
> + ;; (check 'thread-running? thread? t)
We shouldn't drop this check.

2017-05-23 18:55 UTC, samth commented on racket/src/thread/thread.rkt
> +  ( (atomically
Why the extra space?

2017-05-23 18:55 UTC, samth commented on racket/src/thread/thread.rkt
> +       ( (thread-internal-suspend! t #f void block) )
Extra space.

2017-05-23 18:55 UTC, samth commented on racket/src/cs/expander-compat.scm
> -   thread-receive-evt
Let's not remove `thread-recieve-evt` until we add the real one.

2017-05-23 18:55 UTC, samth commented on racket/src/thread/thread.rkt
> +(define (enqueue-mail! thd v)
Can you annotate which functions are called in atomic mode (see other comments in this file)?

2017-05-23 18:58 UTC, spall commented on racket/src/thread/thread.rkt
> + ;; (check 'thread-running? thread? t)
This was accidentally left over from when i was doing the performance testing.

2017-05-23 20:52 UTC, mflatt commented on racket/src/thread/thread.rkt
> +             (loop)))])))))
I agree that atomic mode is needed – and then this covers all of the work of the first atomic block in `thread-receive`, so I'll remove that first one

2017-05-23 21:08 UTC, mflatt commented
This looks generally good! The handling of `thread-waiting-mail?` isn't quite right for interruptions by break events (which could escape without unsetting that flag), so I'll make an adjustment after merging. There's a related issue with `thread-suspend`, which your guard in `thread-send` reminds me to fix.

2017-05-23 21:11 UTC, spall commented on racket/src/thread/thread.rkt
> +             (loop)))])))))
Removing the first block of code will get rid of this line 
```
(set-thread-waiting-mail?! t #t)
``` 
which will cause the code to stop working.    You could move that line of code into the let loop.

2017-05-23 21:12 UTC, mflatt commented
Merged - thanks!

2017-05-23 21:12 UTC, closed without merging